### ISSUE TITLE
miss output_dir in convert_only

### ISSUE THREAD

**Issue by ZIFENG278** [ZillaRU/EmotiVoice-TPU#1]
miss output_dir in convert_only in demo_page.py line 219
```python
save_path = f'{output_dir}/output.wav'
```
new version of gradio Audio component without info attribution, 
if use gradio==4.19.2 the audio support multi sources ['upload', 'microphone'] which can be friendly to use user tone color

for the Error Related to Silero I reference this page https://github.com/myshell-ai/OpenVoice/blob/main/docs/QA.md#issues-with-installation

**Comment by ZillaRU** [comment]
Just fixed the issue with the undefined `output_dir`. Thanks for helping me pinpoint the gradio version for this application! Appreciate the attention to detail.
