### ISSUE TITLE
求助执行最后一步报错了

### ISSUE THREAD

**Issue by Franklin-L** [ZillaRU/EmotiVoice-TPU#2]
求助最后一步执行demopage.py的时候报错请问如何解决呀
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/d18251d0-1f2d-4d29-afbe-04aaa36e0893)

**Comment by ZillaRU** [comment]
目测是gradio版本不兼容导致的报错。
可以用这个命令装一下指定版本的gradio。
pip3 install --upgrade gradio==3.48.0

**Comment by Franklin-L** [comment]
> 目测是gradio版本不兼容导致的报错。 可以用这个命令装一下指定版本的gradio。 pip3 install --upgrade gradio==3.48.0

输出了一个网址但是这个网址无法使用，我用的wifi和微服务器的是一样的

**Comment by Franklin-L** [comment]
> > 目测是gradio版本不兼容导致的报错。 可以用这个命令装一下指定版本的gradio。 pip3 install --upgrade gradio==3.48.0
> 
> 输出了一个网址但是这个网址无法使用，我用的wifi和微服务器的是一样的

解决了解决了

**Comment by Franklin-L** [comment]
> 目测是gradio版本不兼容导致的报错。 可以用这个命令装一下指定版本的gradio。 pip3 install --upgrade gradio==3.48.0

请问一下前辈这个输入的文本是不是有长度限制啊，好像输入过长会报错

**Comment by ZillaRU** [comment]
是的。因为模型推理中shape需要静态化，短的输入会padding到定长，长的没管🤣。如果你想解决这个问题的话，可以改代码给原本的长语句按标点做切分。

**Comment by Franklinlifangcheng** [comment]
> 是的。因为模型推理中shape需要静态化，短的输入会padding到定长，长的没管🤣。如果你想解决这个问题的话，可以改代码给原本的长语句按标点做切分。

请问前辈就是这个模型部署如何缩小占用的运行内容，我只需要第一个基本的文本转语音的功能

**Comment by Franklin-L** [comment]
> 是的。因为模型推理中shape需要静态化，短的输入会padding到定长，长的没管🤣。如果你想解决这个问题的话，可以改代码给原本的长语句按标点做切分。

请问前辈就是这个模型部署如何缩小占用的运行内存，我只需要第一个基本的文本转语音的功能

**Comment by ZillaRU** [comment]
切换到比较早期的版本吧。
git checkout 9c6302e8aa5ee1ba150b92f04078ee374af77ef6

**Comment by Franklin-L** [comment]
> 切换到比较早期的版本吧。 git checkout [9c6302e](https://github.com/ZillaRU/EmotiVoice-TPU/commit/9c6302e8aa5ee1ba150b92f04078ee374af77ef6)

嗷嗷好的那是不是bmodel可以不用换吧只要换TPU文件就可以了吧

**Comment by ZillaRU** [comment]
是的 只改下代码版本 有的模型用不到了 bmodel可能有多余的

**Comment by Franklin-L** [comment]
> 是的 只改下代码版本 有的模型用不到了 bmodel可能有多余的

前辈我用新的但是报错了，我一开始报错一堆库没装，最后报错这个，我的transformer库已经更新了呀
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/71c45666-51f5-414b-87f7-c887c7e17e66)

**Comment by ZillaRU** [comment]
报错是没找到模型文件，检查下model_file目录的结构。

**Comment by Franklinlifangcheng** [comment]
是下面这样的
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/2e6544d6-3c5c-466d-934e-dda4f40060a5)


> 报错是没找到模型文件，检查下model_file目录的结构。

**Comment by Franklinlifangcheng** [comment]
> 报错是没找到模型文件，检查下model_file目录的结构。

嗷嗷我是把tts放在里面了，现在可以了，报了另一个错
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/757d3289-ba92-4b7c-b0be-f1483cb8e5a3)

**Comment by Franklinlifangcheng** [comment]
> > 报错是没找到模型文件，检查下model_file目录的结构。
> 
> 嗷嗷我是把tts放在里面了，现在可以了，报了另一个错 ![image](https://private-user-images.githubusercontent.com/146100070/319993240-757d3289-ba92-4b7c-b0be-f1483cb8e5a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMjAwMzUsIm5iZiI6MTcxMjMxOTczNSwicGF0aCI6Ii8xNDYxMDAwNzAvMzE5OTkzMjQwLTc1N2QzMjg5LWJhOTItNGI3Yy1iMGJlLWYxNDgzY2I4ZTVhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwNVQxMjIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZGQyZTEzYmQwMGViY2I3NjBlMzNlOGQ2ZTJkNWI4YTEwYmVjOWJmNzE5NTkwMDI5MDNhOTE4MmM1ZDRiOTM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lxRyqzfGObtrN1RDSqV8edK5AoheqQcBemFvPzPjWmg)

是需要输入什么吗

**Comment by Franklin-L** [comment]
> 报错是没找到模型文件，检查下model_file目录的结构。

嗷嗷是没有把tts的文件放出来，前辈我现在执行到可以出网页了但是为什么是下面这个样子的
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/7c986e9a-764b-4441-9174-d7f8bb24e72a)
然后我点击submit会报错
![image](https://github.com/ZillaRU/EmotiVoice-TPU/assets/146100070/f37e46e7-5607-488e-809c-6db9614b81fd)

**Comment by ZillaRU** [comment]
页面没加载完全就点submit的话，可能会有比较奇怪的报错。我也没见过页面出来是这样的情况= =
如果只想试一下tts功能不需要页面的话，直接参考这一版的readme，跑这个就可以了。
<img width="875" alt="image" src="https://github.com/ZillaRU/EmotiVoice-TPU/assets/25343084/18278dc6-9462-47fe-90cd-8ea97904fbf2">

**Comment by Franklin-L** [comment]
> 页面没加载完全就点submit的话，可能会有比较奇怪的报错。我也没见过页面出来是这样的情况= = 如果只想试一下tts功能不需要页面的话，直接参考这一版的readme，跑这个就可以了。 <img alt="image" width="875" src="https://private-user-images.githubusercontent.com/25343084/320169305-18278dc6-9462-47fe-90cd-8ea97904fbf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODEyNjUsIm5iZiI6MTcxMjQ4MDk2NSwicGF0aCI6Ii8yNTM0MzA4NC8zMjAxNjkzMDUtMTgyNzhkYzYtOTQ2Mi00N2ZlLTkwY2QtOGVhOTc5MDRmYmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA5MDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5YjA1MjlkYzJiZDM5Njk2MmQ5ZGVkOTBhNGU2OTc1Yzk3M2EyN2MyNDZiYTVlYWEzYjNmYjc2ODBkY2ViZTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Mz8tqPZgcex_tpF-xn56YeYp9vxrsN1iV3Q0Z7ZsyE">

嗷嗷好的前辈，那有没有办法将这个声音在BM1684X的扬声器输出呢，这个您试过吗

**Comment by ZillaRU** [comment]
我做这套demo的时候，盒子还没有扬声器呢。。应该是可以的，参考alsa或portaudio。

**Comment by ZillaRU** [comment]
🤣问了这么多 点个star吧。。。

**Comment by Franklin-L** [comment]
> 🤣问了这么多 点个star吧。。。

哈哈好嘞必须滴

**Comment by Franklin-L** [comment]
> 我做这套demo的时候，盒子还没有扬声器呢。。应该是可以的，参考alsa或portaudio。

alsa或portaudio也是针对这个盒子的项目吗

**Comment by ZillaRU** [comment]
这个搜一下Python alsa或者Python portaudio就有

**Comment by Franklin-L** [comment]
> 这个搜一下Python alsa或者Python portaudio就有
嗷嗷成功了前辈，今天找官方的技术人员要了脚本代码，接下来我就试着去切分对话实现长对话输出了，谢谢前辈的耐心指导

**Comment by Franklin-L** [comment]
> 这个搜一下Python alsa或者Python portaudio就有

刚刚切分确实可以输出长文本了，但是语气好怪异
