### ISSUE TITLE
how to convert models to bmodel?

### ISSUE THREAD

**Issue by zhangw864680355** [ZillaRU/EmotiVoice-TPU#4]
How to convert models to bmodel? Can you provide a reference example? Thanks.

**Comment by ZillaRU** [comment]
To convert a pytorch model to its corresponding bmodel, you need first convert it to onnx/jit model, and then convert the onnx/jit model to a bmodel.

You can refer to the example in [XInstructBLIP-TPU](https://github.com/ZillaRU/XInstructBLIP-TPU/tree/master/trace/InstructBLIP) (`trace_others.py` for `pth model -> onnx/jit model`, `compile_others.py` for `onnx/jit model -> bmodel`) and docs in [tpu-mlir quickstart](https://tpumlir.org/docs/quick_start/03_onnx.html).
