### ISSUE TITLE
how to download tts models in model_file/tts directory？

### ISSUE THREAD

**Issue by zhangw864680355** [ZillaRU/EmotiVoice-TPU#5]
I fail to download models by "python3 -m dfn --url https://disk.sophgo.vip/sharing/KymDuWLGw".
I try to download models by baidu network disk and google network disk，both files look the same.

The checkpoints directory is organized as:
.
├── base_speakers
│   ├── EN
│   │   ├── checkpoint.pth
│   │   ├── config.json
│   │   ├── decoder_1024_f16.bmodel
│   │   ├── decoder_1024_f32.bmodel
│   │   ├── en_default_se.pth
│   │   └── en_style_se.pth
│   └── ZH
│       ├── checkpoint.pth
│       ├── config.json
│       ├── decoder_1024_f16.bmodel
│       └── zh_default_se.pth
└── converter
    ├── checkpoint.pth
    ├── config.json
    ├── decoder_1024_f16.bmodel
    └── decoder_2048_f16.bmodel

how to download tts models as follow:
model_file
└── tts
    ├── am_durationpred-1_512_384-1_512_1.bmodel
    ├── am_energypred-1_512_384-1_512_1.bmodel
    ├── am_pitchpred-1_512_384-1_512_1.bmodel
    ├── am_rest_weight.pth
    ├── bert_poolout1-768_1-512_1-512_1-512.bmodel
    ├── hifigan_1-80-1024_F16.bmodel
    ├── jit_am_encoder_1-512-384_1-1-512.bmodel
    └── onnx_am_decoder_1-2048-384.bmodel

**Comment by ZillaRU** [comment]
TTS models can be downloaded from baidu network disk. 
https://pan.baidu.com/s/1SETXyzYr7PVufpw09WIoMA?pwd=aibx

**Comment by zhangw864680355** [comment]
By downloading the file link you provided, I can run the program demo, thank you.
